# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_datapoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='labels',
            field=models.ManyToManyField(to='lab.Label'),
        ),
    ]
