# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20161114_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='weight',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
