# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_datapoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 18, 16, 17, 1, 579255, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
