# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20161129_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='dataset',
            field=models.ManyToManyField(blank=True, to='lab.Dataset'),
        ),
    ]
